name: phasetida_flutter
description: "A simple Phigros chart player in Flutter, runs in web"
version: 0.1.7
publish_to: none
homepage: https://github.com/phasetida/phasetida_flutter

environment:
  sdk: ^3.10.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  assets:
    - assets/
    - assets/phasetida-node-demo/
    - assets/phasetida-node-demo/assets/
    - assets/phasetida-node-demo/click/
    - assets/phasetida-node-demo/note/
    - assets/phasetida-node-demo/splash/